@startuml

title Relationships - Class Diagram


class Controller
class RequestModel
interface UseCaseBoundary
class ResponseModel
class UseCase
interface Gateway
interface Repository
class DomainModel
class GatewayImpl
class RepositoryImpl
interface Publisher
class PublisherImpl

RequestModel "1" *-up- Controller
ResponseModel "1" *-up- Controller
UseCaseBoundary "1" *-up- Controller

Repository "1" *-up- UseCase
Gateway "1" *-up- UseCase
Publisher "1" *-up- UseCase

RequestModel "1" *-down- UseCase
ResponseModel "1" *-down- UseCase

DomainModel "1" *-up- UseCase

DomainModel "1" *-up- Gateway
DomainModel "1" *-up- Repository
DomainModel "1" *-up- Publisher

Gateway <|-down- GatewayImpl: Inheritance
Repository <|-down- RepositoryImpl: Inheritance
UseCaseBoundary <|-down- UseCase: Inheritance
Publisher <|-down- PublisherImpl: Inheritance


@enduml